services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Webandwork\ContaoCleverreachConnectorBundle\Api\ApiManager:
        public: true

    Webandwork\ContaoCleverreachConnectorBundle\Cron\RefreshCleverreachTokenCron:
        tags:
            -   name: contao.cronjob
                interval: 0 */2 * * *
                method: onEveryTwoHours

